apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-ws
  labels:
    app: demo-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-ws
  template:
    metadata:
      labels:
        app: demo-ws
    spec:
      containers:
      - name: demo-ws
        image: angelorum/demo-configmap:0.0.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: application-config 
          mountPath: "/config"
      volumes:
        - name: application-config
          configMap:
            name: spring-app-config 
            items:
            - key: application.properties 
              path: application.properties